name: Windows MSBuild

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [Win32, x64]   # Win32 = x86 u Visual Studiu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: NuGet restore (optional)
        run: |
          if (Test-Path ".\TaktickaPloca.sln") { nuget restore .\TaktickaPloca.sln } else { echo "Skip restore" }

      - name: Build
        run: |
          msbuild .\TaktickaPloca.sln /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TaktickaPloca-${{ matrix.platform }}-${{ matrix.configuration }}
          path: |
            **\${{ matrix.configuration }}\*.exe
            **\${{ matrix.configuration }}\*.pdb
          if-no-files-found: warn